#!/usr/bin/env bash
#Installs Nginx web server
#Nginx should be listening on port 80
#When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the #string Hello World!
#As an answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will b#e run on the server itself)
#You can’t use systemctl for restarting nginx

sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo ufw allow 80
sudo service nginx restart
