#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

#Requirements:

#Configure HAproxy so that it send traffic to web-01 and web-02
#Distribute requests using a roundrobin algorithm
#Make sure that HAproxy can be managed via an init script
#Make sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02. If not, follow this tutorial.
#For your answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y haproxy
sudo echo "Enabled=1" | sudo tee -a /etc/default/haproxy
sudo echo -e "\nfrontend load_balancer\n\tbind *:80\n\tdefault_backend myservers\n\nbackend myservers\n\tbalance roundrobin\n\tserver web-01 18.206.232.169\n\tserver web-02 35.153.18.29\n" | sudo tee -a haproxy.cfg.new
sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo service haproxy restart
