#!/usr/bin/env bash
# Ping an address

if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ip_address="$1"
    echo "PING $ip_address"
    ping "$ip_address" -c 5
fi
