#!/usr/bin/env bash
# Finds and terminates the 7-highlander process

process_ids=$(pgrep -f "7-highlander")

if [ -n "$process_ids" ]; 
then
    for pid in $process_ids;
    do
        kill -9 "$pid"
    done
fi
