#!/usr/bin/env bash
#displays Best School 10 times
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#display best school on other iterations

n=1
while ((n <= 10))
do
	if ((n == 4));
	then
		echo "bad luck"
	elif ((n == 8));
	then
		echo "good luck"
	else
		echo "Best school"
	fi
	n=$((n + 1))
done
