#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 20 and:
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration

n=1

while ((n <= 20))
do
	if ((n == 4));
	then
		echo $n
		echo "bad luck from China"
	elif ((n == 9));
	then
		echo $n
		echo "bad luck from Japan"
	elif ((n == 17));
	then
		echo $n
		echo "bad luck from Italy"
	else
		echo $n
	fi
	((n++))
done
