#!/usr/bin/env bash
#configure ufw to disable all incoming traffic except on TCP ports 22, 80, and 443
sudo apt-get update -y
sudo apt-get install ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 80
sudo ufw allow 443
sudo ufw allow 22
sudo ufw enable