#!/usr/bin/env bash

if grep -q -i "localhost" "$1"; then
sudo sudo sed -i 's/^[0-9.]\+[[:space:]]\+localhost/127.0.0.2 localhost/' "$1"
else
sudo echo "127.0.0.2 localhost/n8.8.8.8 facebook\n" | sudo tee -a "$1"
fi
