#!/usr/bin/env bash
# Displays all IPv4 IPs on a machine

if command -v ifconfig &> /dev/null; then
    ifconfig | grep -oP '(?<=inet )[\d.]+'
elif command -v ip &> /dev/null; then
    ip -o -4 addr show | awk '{print $4}' | cut -d'/' -f1
    exit 1
fi
