#!/usr/bin/env bash
#starts nginx as nginx user, and nginx listens to all IPs on port 8080
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/sites-available/default
sudo sed -i 's/listen 80 default_server;/listen 0.0.0.0:80;/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
